import { jsPDF } from 'jspdf';
import { TestAttempt } from '../types';

export function generateResultPDF(attempt: TestAttempt) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Header Banner
  doc.setFillColor(30, 58, 138); // Deep Navy Primary
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('MOCK TEST SERIES PERFORMANCE REPORT', 14, 18);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth - 14, 18, { align: 'right' });

  y = 38;

  // Student & Test Details Card
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, y, pageWidth - 28, 38, 3, 3, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(`Test Title: ${attempt.testTitle}`, 20, y + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Student Name: ${attempt.student.name}`, 20, y + 18);
  doc.text(`Email: ${attempt.student.email}`, 20, y + 25);
  doc.text(`Phone: ${attempt.student.phone}`, 20, y + 32);

  doc.text(`Attempt ID: ${attempt.id.slice(0, 8)}`, pageWidth - 20, y + 18, { align: 'right' });
  doc.text(`Completed: ${new Date(attempt.submittedAt).toLocaleString()}`, pageWidth - 20, y + 25, { align: 'right' });
  doc.text(`Time Spent: ${Math.floor(attempt.timeTakenSeconds / 60)}m ${attempt.timeTakenSeconds % 60}s`, pageWidth - 20, y + 32, { align: 'right' });

  y += 46;

  // Key Metrics Grid
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Scorecard Summary', 14, y);

  y += 6;

  const cardWidth = (pageWidth - 28 - 12) / 4;
  const metrics = [
    { label: 'Score Obtained', val: `${attempt.score} / ${attempt.totalMarks}`, color: [37, 99, 235] },
    { label: 'Percentage', val: `${attempt.percentage.toFixed(1)}%`, color: [16, 185, 129] },
    { label: 'Status', val: attempt.passed ? 'PASSED' : 'FAILED', color: attempt.passed ? [16, 185, 129] : [239, 68, 68] },
    { label: 'Accuracy', val: `${attempt.correctCount + attempt.incorrectCount > 0 ? Math.round((attempt.correctCount / (attempt.correctCount + attempt.incorrectCount)) * 100) : 0}%`, color: [124, 58, 237] },
  ];

  metrics.forEach((m, idx) => {
    const x = 14 + idx * (cardWidth + 4);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(x, y, cardWidth, 22, 2, 2, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(m.label, x + cardWidth / 2, y + 7, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(m.color[0], m.color[1], m.color[2]);
    doc.text(m.val, x + cardWidth / 2, y + 16, { align: 'center' });
  });

  y += 30;

  // Question Breakdown Stats
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Question Performance Breakdown', 14, y);

  y += 6;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(203, 213, 225);
  doc.rect(14, y, pageWidth - 28, 20, 'D');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(22, 101, 52); // Green
  doc.text(`Correct: ${attempt.correctCount}`, 24, y + 12);

  doc.setTextColor(153, 27, 27); // Red
  doc.text(`Incorrect: ${attempt.incorrectCount}`, 74, y + 12);

  doc.setTextColor(100, 116, 139); // Gray
  doc.text(`Unattempted: ${attempt.unattemptedCount}`, 124, y + 12);

  doc.setTextColor(180, 83, 9); // Amber
  doc.text(`Proctor Warnings: ${attempt.tabSwitchCount}`, 168, y + 12);

  y += 28;

  // Footer Note
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('This performance report is automatically generated by Mock Test Series Platform.', pageWidth / 2, 285, { align: 'center' });

  // Save File
  const safeName = attempt.student.name.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${safeName}_Scorecard_${attempt.testTitle.substring(0, 15)}.pdf`);
}
